"""add advance_salary table and advance_balance to employees

Revision ID: 267038f7d926
Revises: 6314d3293add
Create Date: 2026-07-12 22:43:09.469634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267038f7d926'
down_revision: Union[str, None] = '6314d3293add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advance_salary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_recovered', sa.Boolean(), nullable=False),
    sa.Column('recovered_month', sa.String(length=7), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advance_salary_employee_id'), 'advance_salary', ['employee_id'], unique=False)
    op.create_index(op.f('ix_advance_salary_org_id'), 'advance_salary', ['org_id'], unique=False)
    op.add_column('employees', sa.Column('advance_balance', sa.Numeric(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'advance_balance')
    op.drop_index(op.f('ix_advance_salary_org_id'), table_name='advance_salary')
    op.drop_index(op.f('ix_advance_salary_employee_id'), table_name='advance_salary')
    op.drop_table('advance_salary')
    # ### end Alembic commands ###
