"""add tax fields to organizations

Revision ID: 42eb216ba878
Revises: b1bbf2712c0f
Create Date: 2026-07-07 23:15:22.147230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42eb216ba878'
down_revision: Union[str, None] = 'b1bbf2712c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
