"""add employees and payslips tables

Revision ID: 6ec2889fbe4e
Revises: 42eb216ba878
Create Date: 2026-07-09 03:48:11.960588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec2889fbe4e'
down_revision: Union[str, None] = '42eb216ba878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnic', sa.String(length=15), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('eobi_employee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('eobi_employer', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'terminated', name='employeestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_org_id'), 'employees', ['org_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('eobi_deduction', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('income_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('other_deductions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_org_id'), 'payslips', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslips_org_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_employees_org_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
