"""make invoice contact_id nullable

Revision ID: b1bbf2712c0f
Revises: 9b8c446ec11e
Create Date: 2026-07-05 03:44:34.401693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1bbf2712c0f'
down_revision: Union[str, None] = '9b8c446ec11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'contact_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'contact_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
